stages:
  data_split:
    cmd: python data_split.py
    deps:
    - data/train.csv
    - data_split.py
    params:
    - data_split.seed
    - data_split.test_size
    outs:
    - data/train_split.csv
    - data/test_split.csv

  normalize:
    cmd: python normalize.py
    deps:
    - normalize.py
    - data/train_split.csv
    outs:
    - data/features/train.csv
    - data/features/test.csv
    - artifacts/scaler.joblib

  train:
    cmd: python train.py
    deps:
    - train.py
    - data/features/train.csv
    params:
    - train.shrinkage
    outs:
    - artifacts/clf.joblib

  evaluate:
    cmd: python evaluate.py
    deps:
    - evaluate.py
    - data/features/train.csv
    - data/features/test.csv
    - artifacts/clf.joblib
    metrics:
    - metrics.json:
        cache: false
